### ISSUE TITLE
数据构造和训练时用户交互的差异

### ISSUE THREAD

**Issue by jack-wxm** [tangqiaoyu/ToolAlpaca#1]
Tool-use Instance Generation阶段构造数据时会有与用户agent交互的地方，会让用户补齐参数，所以Action: chatWithUser，但是我在训练数据中没有发现chatWithUser这个Action，是直接把用户交互补齐的参数直接放到action input里面了吗，训练时是设定参数完整这个前提吗？

**Comment by tangqiaoyu** [comment]
您好，在这一版本数据中使用的相对应的 Action 名称为 `getDetails`。

**Comment by jack-wxm** [comment]
谢谢解答，我还有个问题是gpt3.5过程和结果准确率都是80+，那用gpt3.5测试的时候，都会把哪些信息放进prompt里面？因为训练集里面我看NLDocumentation以及Documentation都非常长，已经超过了3.5最大输入长度了，这个时候工具信息是怎么塞进去的？

**Comment by tangqiaoyu** [comment]
NLDocumentation 是没有超过最大输入长度的

**Comment by jack-wxm** [comment]
哦哦，意思是只把NLDocumentation放入prompt中对吧

**Comment by tangqiaoyu** [comment]
是的，当然也可以对 Documentation 进行一定的转换后放入 prompt 中，这两个不需要同时存在

**Comment by jack-wxm** [comment]
好的，那你们是会给gpt3.5你们的格式示例么，这样它才能按照你们的格式输出？

**Comment by tangqiaoyu** [comment]
会给格式示例，具体可以参照 [LangChain](https://github.com/hwchase17/langchain)

**Comment by jack-wxm** [comment]
好的，再次感谢解答

**Comment by better629** [comment]
> getDetails

@tangqiaoyu Can you share the prompt template from train_data instance to Vicuna conversation example?
