### ISSUE TITLE
typo in evaluation.py

### ISSUE THREAD

**Issue by mattgithub1919** [tangqiaoyu/ToolAlpaca#12]
Thanks for the great work. I ran the last step of evaluation which is `evaluation.py` but failed due to several errors. They could be some typos but I'm not sure. I thus open this ticket, looking to discuss with you. 

>   File "evaluation.py", line 81, in <module>
    solution += f"{sol_id + 2}. Final Response: {api_info['Answers'][ques_id]['output']}"
KeyError: 'Answers'
- should it be 'Instances' instead?

> Traceback (most recent call last):
  File "evaluation.py", line 84, in <module>
    documentation=api_info["api_description"],
KeyError: 'api_description'
- should it be 'Function_Description' instead? (I'm not 100% sure about this)

> is lines 118-123 really needed? we already have lines 124-129

> probably need to add file name in line 126 after `os.path.join(args.output_path`. 

Kindly correct me if I'm wrong. Thanks.

**Comment by tangqiaoyu** [comment]
Hi,

Thank you for pointing out the typos and raising these issues. I truly appreciate your diligence.

Regarding your first two points, you're absolutely correct. Those were indeed typos in my code. I have updated the `Answers` to `Instances` and `api_description` to `NLDocumentation` in the code. 

As for the lines 118-123, these lines of code are designed to provide real-time results during the evaluation process. If you don't need this feature, feel free to comment them out.
