### ISSUE TITLE
error in evaluation -- connection

### ISSUE THREAD

**Issue by shadii4** [tangqiaoyu/ToolAlpaca#16]
when i run evaluation
# get LLM outputs
python instance_generation/generation.py \
  -api ./data/eval_simulated.json \
  -out ./eval \
  -llm ./outputs/model1 \
  --agent_prompt test_v1 \
  
  I get an error: ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5678): Max retries exceeded with url: /Axolotl/random (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f635fb4c5b0>: Failed to establish a 
new connection: [Errno 111] Connection refused'))

Can you help me with this please, thanks!

**Comment by tangqiaoyu** [comment]
Hi, you should start the API simulator first.
```bash
python instance_generation/simulator.py -api ./data/eval_simulated.json
```
