### ISSUE TITLE
https://api.publicapis.org/entries 网址现在打不开了

### ISSUE THREAD

**Issue by luckierya** [tangqiaoyu/ToolAlpaca#21]
大佬，您好，现在这个 https://api.publicapis.org/entries 网址打不开了。不能下载data/public_apis.json 数据

**Comment by tangqiaoyu** [comment]
你好，我已经将我当时下载的`data/public_apis.json`上传了，你可以下载一下

**Comment by luckierya** [comment]
好的，感谢



在 2024-07-04 15:41:13，"Tang Qiaoyu" ***@***.***> 写道：

你好，我已经将我当时下载的data/public_apis.json上传了，你可以下载一下
