### ISSUE TITLE
Model Weights?

### ISSUE THREAD

**Issue by VenkatKS** [tangqiaoyu/ToolAlpaca#5]
Hello!

Thank you for your incredible work here, as well as releasing your data scripts. I was wondering if you would consider releasing the model you've trained and reported metrics on in the paper? It would be great to give the model a try on new APIs! 

Thank you again!

**Comment by tangqiaoyu** [comment]
Thank you for your kind words and interest in our work. The trained models are now available on Hugging Face Hub. You can find them at the following links:

- [ToolAlpaca-7B](https://huggingface.co/TangQiaoYu/ToolAlpaca-7B)
- [ToolAlpaca-13B](https://huggingface.co/TangQiaoYu/ToolAlpaca-13B)

For usage and evaluation, please refer to the 'Evaluation' section in the README. I hope this helps and I look forward to any further questions or feedback you may have.
