### ISSUE TITLE
generation

### ISSUE THREAD

**Issue by YangQianli92** [tangqiaoyu/ToolAlpaca#9]
"Thank you for the open-source code and the detailed usage instructions you provided.
 I've encountered an issue when running the command 
`python instance_generation/generation.py -api ./data/api_data.json -out ./data --use_cache`. 
The error message I received is: 
`TypeError: CustomAgentExecutor._take_next_step() got an unexpected keyword argument 'run_manager'. `
I'm not sure what could be causing this issue, but I suspect it might be due to different versions of Langchain. Could you please provide the version you used?"

**Comment by tangqiaoyu** [comment]
The version of Langchain I used when developing this project is 0.0.147. Please try using this version and let me know if you continue to encounter the same error.
